"""Project scaffolding: ``eglk-harness init``."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from eglk_harness.domain.kernel import paths

_DEFAULT_CONFIG = """\
# Generated by `eglk-harness init` · do not put API keys here

[run]
default_agent = "codex"          # codex | claude_code | mock
workdir = "."
compile = "auto"                 # auto | force | off
swarm = "auto"                   # auto | off | on

[models]
# Empty → fall back to EGLK_MODEL / default
# maker = ""
# checker = ""
# governor = ""

[budgets]
# Episode timeouts (seconds); env EGLK_TIMEOUT_* also works
# maker = 600
# checker = 600
# governor = 120
# explorer = 120
# verifier = 120
# refiner = 120

[limits]
# Defaults: design/kernel/projections.md
# cognitive_tokens_max = 64000
# repairs_max = 8
# max_ticks_soft = 0

[mcp]
# config = "/path/to/mcp.json"
# add_dirs = []

[observe]
dashboard = false                # read-only only; never an approval gate
# prompt_language = "en"         # en | zh (EGLK_PROMPT_LANGUAGE)
"""

_DEFAULT_GOAL = """\
# Goal

> Human-authored goal (read-only for models at runtime).

## Summary

TODO: one-sentence goal.

## Done criteria

- [ ] TODO: verifiable completion criterion

## Constraints

- Do not modify this file during a run.
"""


@dataclass
class InitResult:
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def init_project(workdir: Path, *, force: bool = False) -> InitResult:
    """Create `.eglk-harness/` skeleton and `.goal.md` placeholder.

    Does not write API keys. Existing files are skipped unless ``force``.
    """
    workdir = workdir.resolve()
    result = InitResult()

    def _write(path: Path, content: str) -> None:
        rel = str(path.relative_to(workdir))
        if path.exists() and not force:
            result.skipped.append(rel)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        result.created.append(rel)

    def _ensure_dir(path: Path) -> None:
        rel = str(path.relative_to(workdir))
        if path.is_dir():
            result.skipped.append(rel + "/")
            return
        path.mkdir(parents=True, exist_ok=True)
        result.created.append(rel + "/")

    _ensure_dir(paths.harness_root(workdir))
    _ensure_dir(paths.loop_root(workdir))
    _ensure_dir(paths.memory_root(workdir))
    _ensure_dir(paths.memory_sigma_dir(workdir))
    _ensure_dir(paths.memory_skills_dir(workdir))

    _write(paths.config_path(workdir), _DEFAULT_CONFIG)
    _write(paths.goal_path(workdir), _DEFAULT_GOAL)

    # Empty active/archived placeholders for Σ
    sigma = paths.memory_sigma_dir(workdir)
    _write(sigma / "active.json", "[]\n")
    _write(sigma / "archived.json", "[]\n")

    return result
